name: "crc"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-crc]
  schedule:
    - cron: '10 * * * *'
    - cron: '40 * * * *'

jobs:
  crc:
    uses: invalidunit/check_change/.github/workflows/crc_bark.yml@main
    secrets:
      _key: ${{ secrets._key }}

  remove_all_old_actions:
    uses: invalidunit/action/.github/workflows/remove_all_actions.yml@main
